### ISSUE TITLE
How to use pre-made model

### ISSUE THREAD

**Issue by ccallahan** [NickBrisebois/DiscordChatAI-GPT2#3]
Hey! Admittedly I just came across this, but how hard would it be to use a model I've already generated?

**Comment by johnnymcmike** [comment]
Hi, was in your same boat for a while until I figured it out. Assuming that you're like me and trying to use the bot with a model you've already finetuned, you've gotta clone the repo, start from scratch, and then copy your .tar file of the checkpoint to that directory. Decompress it so that it this directory now has a "checkpoint" folder in it.

From here you want to download the model that your pretrained model is based on. This will be 124M, 355M, etc. To do this you want to (in that same directory) enter the python interpreter and then run `gpt2.download_gpt2(model_name="124M")` for example. After this, you want to exit python and then change the "MODEL_NAME" variable in main.py to whatever you just downloaded in that command.

If all goes well, after this you'll be able to run `python main.py -t` and test out your model. Not sure this is the cleanest or easiest or correctest way of doing this, but it worked for me and I'll respond to this if I discover something better.
