### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by wtfismyname69420** [NickBrisebois/DiscordChatAI-GPT2#5]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\user\Desktop\Chat bot\Bot\bot.py", line 41, in on_message
    if random.random() > float(self.response_chance) and has_mentioned == True:
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by NickBrisebois** [comment]
Hi, what command are you running the script with?

**Comment by wtfismyname69420** [comment]
Just trying to run the bot

**Comment by wtfismyname69420** [comment]
so python main.py --token 
Also what format is the chat format in?
I'm not sure what the correct chat format
Can it only have 2 people or more than 2?
Does it have to be person 1, person 2 or can it be like actual discord name?

**Comment by NickBrisebois** [comment]
> so python main.py --token

I'd recommend using the docker version if you're comfortable with that. It configures the environment for you so you don't run into obscure issues due to your locally installed dependencies. 

> Also what format is the chat format in?
> I'm not sure what the correct chat format

Since it's just training on raw data, it can be in any format you like as long as it's a text file.

> Can it only have 2 people or more than 2?

Either works. I use all messages without any usernames attached.

> Does it have to be person 1, person 2 or can it be like actual discord name?

Depends on how you export your discord chat log. If you're using my [scraper](https://github.com/NickBrisebois/DiscordServerMessageScraper), it has the mentioned usernames as user IDs
